language: python
python:
  - "2.6"
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - mysql-server
      - python-dev
      - libmysqlclient-dev
      - redis-server

install: make setup

script: make ci-test
