language: python
python:
  - "2.6"
  - "2.7"
  - "3.5.1"
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true
  allow_failures:
    - python: '3.5.1'
sudo: false
addons:
  apt:
    packages:
      - mysql
      - python-dev
      - libmysqlclient-dev
      - redis-server

install: make setup

script: make ci-test
